spring:
  cloud:
    stream:
      rocketmq:
        bindings:
          # channel名称, 与spring.cloud.stream.bindings下的channel名称对应
          Topic-test1:
            consumer:
              # 订阅的tag类型， 默认订阅所有消息
              subscription: TAG1
          # channel名称
          Topic-test2:
            consumer:
              subscription: TAG2
        binder:
          # 服务地址全称
          name-server: rocketmq-xxx.rocketmq.ap-bj.public.tencenttdmq.com:9876
          # 角色名称
          secret-key: admin
          # 角色密钥
          access-key: eyJrZXlJZC....
          # namespace全称
          namespace: rocketmq-xxx|namespace1
          # 生产者group名称
          group: group99
      bindings:
        # channel名称
        Topic-send:
          # 指定topic, 对应创建的topic名称
          destination: topictest1
          content-type: application/json
          # 要使用group名称
          group: group99
        # channel名称
        Topic-test1:
          destination: topictest1
          content-type: application/json
          group: group99
        # channel名称
        Topic-test2:
          destination: topictest1
          content-type: application/json
          group: group88

server:
  port: 9999
