spring:
  cloud:
    stream:
      rocketmq:
        binder:
          # 服务地址全称
          name-server: rocketmq-xxx.rocketmq.ap-bj.public.tencenttdmq.com:9876
          # 角色名称
          secret-key: admin
          # 角色密钥
          access-key: eyJrZXlJZ...
          # namespace全称
          namespace: rocketmq-xxx|namespace1
          # producer group
          group: producerGroup
        bindings:
          # channel名称, 与spring.cloud.stream.bindings下的channel名称对应
          Topic-TAG1-Input:
            consumer:
              # 订阅的tag类型，根据消费者实际情况进行配置（默认是订阅所有消息）
              subscription: TAG1
          # channel名称
          Topic-TAG2-Input:
            consumer:
              subscription: TAG2
      bindings:
        # channel名称
        Topic-send-Output:
          # 指定topic, 对应创建的topic名称
          destination: TopicTest
          content-type: application/json
        # channel名称
        Topic-TAG1-Input:
          destination: TopicTest
          content-type: application/json
          group: consumer-group1
        # channel名称
        Topic-TAG2-Input:
          destination: TopicTest
          content-type: application/json
          group: consumer-group2
