spring:
  cloud:
    function:
      definition: topicTag1;topicTag2
    stream:
      rocketmq:
        binder:
          # 服务地址全称
          name-server: rocketmq-xxx.rocketmq.ap-bj.public.tencenttdmq.com:9876
          # 角色名称
          secret-key: admin
          # 角色密钥
          access-key: eyJrZXlJZ...
          # namespace全称
          namespace: rocketmq-xxx|namespace1
          # producer group
          group: producerGroup
        bindings:
          # binding名称, 与spring.cloud.stream.bindings下的binding名称对应
          topicTag1-in-0:
            consumer:
              # 订阅的tag类型，根据消费者实际情况进行配置（默认是订阅所有消息）
              subscription: TAG1
          # binding名称
          topicTag2-in-0:
            consumer:
              subscription: TAG2
      bindings:
        # binding名称，生产者通过 StreamBridge 发送到 topicSend-out-0
        topicSend-out-0:
          # 指定topic, 对应创建的topic名称
          destination: TopicTest
          content-type: application/json
        # binding名称，消费者函数 topicTag1 的输入 binding
        topicTag1-in-0:
          destination: TopicTest
          content-type: application/json
          group: consumer-group1
        # binding名称，消费者函数 topicTag2 的输入 binding
        topicTag2-in-0:
          destination: TopicTest
          content-type: application/json
          group: consumer-group2
